name: System Logs Sync
on:
  schedule:
    - cron: "0 */2 * * *" # اجرای خودکار هر ۲ ساعت
  workflow_dispatch: # امکان اجرای دستی برای تست
jobs:
  maintenance-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        run: |
          pip install telethon requests pyzipper
      - name: Execute Sync
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          IDS_500: ${{ secrets.IDS_500 }}
          CHANNELS_500: ${{ secrets.CHANNELS_500 }}
          IDS_50: ${{ secrets.IDS_50 }}
          CHANNELS_50: ${{ secrets.CHANNELS_50 }}
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: python main.py
